"use strict";

// Node.js generation script for protection.js
// This generates all 100 categories with 10 methods each (1000 methods total)

const fs = require('fs');

// All 100 categories: [moduleKey, displayName, shortName]
const categories = [
  ['memoryDynamic', '1. Memory Dynamic Protection', 'Memory Dynamic'],
  ['processIsolation', '2. Process Isolation', 'Process Isolation'],
  ['filesystemIntegrity', '3. Filesystem Integrity', 'Filesystem Integrity'],
  ['networkDefense', '4. Network Defense', 'Network Defense'],
  ['registryProtection', '5. Registry Protection', 'Registry Protection'],
  ['bootProtection', '6. Boot Protection', 'Boot Protection'],
  ['injectionDefense', '7. Injection Defense', 'Injection Defense'],
  ['pipeSecurity', '8. Pipe Security', 'Pipe Security'],
  ['driverProtection', '9. Driver Protection', 'Driver Protection'],
  ['codeObfuscation', '10. Code Obfuscation', 'Code Obfuscation'],
  ['apiProtection', '11. API Protection', 'API Protection'],
  ['stackProtection', '12. Stack Protection', 'Stack Protection'],
  ['vulnDetection', '13. Vulnerability Detection', 'Vulnerability Detection'],
  ['privilegeControl', '14. Privilege Control', 'Privilege Control'],
  ['sleepProtection', '15. Sleep Protection', 'Sleep Protection'],
  ['timestampDefense', '16. Timestamp Defense', 'Timestamp Defense'],
  ['hookProtection', '17. Hook Protection', 'Hook Protection'],
  ['accountSecurity', '18. Account Security', 'Account Security'],
  ['callbackProtection', '19. Callback Protection', 'Callback Protection'],
  ['dnsDefense', '20. DNS Defense', 'DNS Defense'],
  ['loginProtection', '21. Login Protection', 'Login Protection'],
  ['filechangeDefense', '22. File Change Defense', 'File Change Defense'],
  ['clipboardSecurity', '23. Clipboard Security', 'Clipboard Security'],
  ['keyboardProtection', '24. Keyboard Protection', 'Keyboard Protection'],
  ['printSecurity', '25. Print Security', 'Print Security'],
  ['dnsProtection', '26. DNS Protection', 'DNS Protection'],
  ['dhcpDefense', '27. DHCP Defense', 'DHCP Defense'],
  ['arpProtection', '28. ARP Protection', 'ARP Protection'],
  ['bluetoothSecurity', '29. Bluetooth Security', 'Bluetooth Security'],
  ['wifiSecurity', '30. WiFi Security', 'WiFi Security'],
  ['usbProtection', '31. USB Protection', 'USB Protection'],
  ['logSecurity', '32. Log Security', 'Log Security'],
  ['scheduledTask', '33. Scheduled Task', 'Scheduled Task'],
  ['restorePoint', '34. Restore Point', 'Restore Point'],
  ['serviceProtection', '35. Service Protection', 'Service Protection'],
  ['permissionSync', '36. Permission Sync', 'Permission Sync'],
  ['apiAudit', '37. API Audit', 'API Audit'],
  ['injectionImmune', '38. Injection Immunity', 'Injection Immunity'],
  ['stackIsolation', '39. Stack Isolation', 'Stack Isolation'],
  ['filesystemObfuscation', '40. Filesystem Obfuscation', 'Filesystem Obfuscation'],
  ['heapProtection', '41. Heap Protection', 'Heap Protection'],
  ['aslrEnhancement', '42. ASLR Enhancement', 'ASLR Enhancement'],
  ['tlsHardening', '43. TLS Hardening', 'TLS Hardening'],
  ['kernelBoot', '44. Kernel Boot', 'Kernel Boot'],
  ['driverSigning', '45. Driver Signing', 'Driver Signing'],
  ['debugDefense', '46. Debug Defense', 'Debug Defense'],
  ['hookHardening', '47. Hook Hardening', 'Hook Hardening'],
  ['protocolValidation', '48. Protocol Validation', 'Protocol Validation'],
  ['inputValidation', '49. Input Validation', 'Input Validation'],
  ['memoryPartition', '50. Memory Partition', 'Memory Partition'],
  ['syscallProtection', '51. Syscall Protection', 'Syscall Protection'],
  ['processSnapshot', '52. Process Snapshot', 'Process Snapshot'],
  ['memoryAllocation', '53. Memory Allocation', 'Memory Allocation'],
  ['passwordSecurity', '54. Password Security', 'Password Security'],
  ['identityAuth', '55. Identity Authentication', 'Identity Authentication'],
  ['encryptionKey', '56. Encryption Key Management', 'Encryption Key Management'],
  ['injectionPrevention', '57. Injection Prevention', 'Injection Prevention'],
  ['exceptionHandling', '58. Exception Handling', 'Exception Handling'],
  ['infoFlowControl', '59. Information Flow Control', 'Information Flow Control'],
  ['behaviorAnalysis', '60. Behavior Analysis', 'Behavior Analysis'],
  ['networkIsolation', '61. Network Isolation', 'Network Isolation'],
  ['resourceIsolation', '62. Resource Isolation', 'Resource Isolation'],
  ['asyncSecurity', '63. Async Operation Security', 'Async Operation Security'],
  ['taskQueue', '64. Task Queue Security', 'Task Queue Security'],
  ['moduleIntegrity', '65. Module Integrity', 'Module Integrity'],
  ['sharedMemory', '66. Shared Memory Protection', 'Shared Memory Protection'],
  ['stackReinforcement', '67. Stack Reinforcement', 'Stack Reinforcement'],
  ['filePermission', '68. File Permission Control', 'File Permission Control'],
  ['processIdentity', '69. Process Identity', 'Process Identity'],
  ['trafficAnalysis', '70. Traffic Analysis', 'Traffic Analysis'],
  ['memoryVerification', '71. Memory Verification', 'Memory Verification'],
  ['processSelfDefense', '72. Process Self-Defense', 'Process Self-Defense'],
  ['syscallHardening', '73. Syscall Hardening', 'Syscall Hardening'],
  ['memoryObject', '74. Memory Object Protection', 'Memory Object Protection'],
  ['clockProtection', '75. Clock Protection', 'Clock Protection'],
  ['hardwareDefense', '76. Hardware Defense', 'Hardware Defense'],
  ['kernelObject', '77. Kernel Object', 'Kernel Object'],
  ['userInput', '78. User Input Security', 'User Input Security'],
  ['appConfig', '79. Application Config', 'Application Config'],
  ['keyLifecycle', '80. Key Lifecycle Management', 'Key Lifecycle Management'],
  ['securityEvent', '81. Security Event Management', 'Security Event Management'],
  ['riskAssessment', '82. Risk Assessment', 'Risk Assessment'],
  ['permissionManagement', '83. Permission Management', 'Permission Management'],
  ['cryptoLibrary', '84. Cryptographic Library', 'Cryptographic Library'],
  ['monitorAgent', '85. Security Monitor Agent', 'Security Monitor Agent'],
  ['logProtection', '86. Log Protection', 'Log Protection'],
  ['backupStrategy', '87. Backup Strategy', 'Backup Strategy'],
  ['iamManagement', '88. IAM Management', 'IAM Management'],
  ['incidentResponse', '89. Incident Response', 'Incident Response'],
  ['supplyChain', '90. Supply Chain Security', 'Supply Chain Security'],
  ['virtualization', '91. Virtualization Security', 'Virtualization Security'],
  ['containerSecurity', '92. Container Security', 'Container Security'],
  ['deviceFingerprint', '93. Device Fingerprint', 'Device Fingerprint'],
  ['cloudSecurity', '94. Cloud Security', 'Cloud Security'],
  ['webFirewall', '95. Web Application Firewall', 'Web Application Firewall'],
  ['mobileSecurity', '96. Mobile Device Security', 'Mobile Device Security'],
  ['firmwareSecurity', '97. Firmware Security', 'Firmware Security'],
  ['iotSecurity', '98. IoT Security', 'IoT Security'],
  ['networkSegmentation', '99. Network Segmentation', 'Network Segmentation'],
  ['aiDefense', '100. AI Defense', 'AI Defense'],
];

// Method definitions per category - realistic descriptions
const methodDB = {
  memoryDynamic: [
    ['Heap Spray Detection', 'Detects heap spray attacks by monitoring allocation patterns and NOP sled signatures'],
    ['Stack Pivot Detection', 'Identifies stack pivot techniques used in ROP chain exploitation attempts'],
    ['Return Address Verification', 'Validates return addresses on stack frames before function returns'],
    ['Memory Page Guard', 'Sets guard pages around critical memory regions to detect overflows'],
    ['Allocator Hardening', 'Randomizes heap chunk positions and adds canary values to metadata'],
    ['Use-After-Free Detection', 'Monitors dangling pointer dereferences via deferred free queues'],
    ['Double Free Prevention', 'Tracks freed memory blocks to prevent double-free vulnerabilities'],
    ['Buffer Overflow Guard', 'Enforces bounds checking on dynamic buffer write operations'],
    ['Virtual Memory Monitor', 'Watches virtual memory region changes for suspicious remapping'],
    ['Memory Integrity Hashing', 'Periodically hashes critical memory sections to detect tampering'],
  ],
  processIsolation: [
    ['Sandbox Enforcement', 'Executes untrusted code in restricted sandboxed environments'],
    ['Process Boundary Hardening', 'Strengthens inter-process communication boundary checks'],
    ['Token Isolation', 'Isolates security tokens between processes to prevent token stealing'],
    ['Job Object Containment', 'Uses job objects to limit process resource and privilege scope'],
    ['Desktop Heap Isolation', 'Separates desktop heap allocations per process session'],
    ['Window Message Filtering', 'Filters cross-process window messages for injection attempts'],
    ['Handle Table Protection', 'Protects process handle table from unauthorized external access'],
    ['Address Space Partitioning', 'Partitions virtual address space to isolate sensitive code regions'],
    ['Thread Impersonation Guard', 'Prevents thread impersonation across process boundaries'],
    ['Process Affinity Lock', 'Locks process affinity to prevent cross-NUMA node attacks'],
  ],
  filesystemIntegrity: [
    ['File Checksum Verification', 'Computes and verifies SHA-256 checksums of critical system files'],
    ['Directory Junction Guard', 'Prevents malicious directory junctions from redirecting file access'],
    ['NTFS Stream Scanner', 'Scans alternate NTFS data streams for hidden malicious payloads'],
    ['File Attribute Monitor', 'Monitors file attribute changes for suspicious hidden or system flags'],
    ['Symbolic Link Validation', 'Validates symbolic link targets to prevent link-based privilege escalation'],
    ['Mount Point Security', 'Secures volume mount points against unauthorized remounting attempts'],
    ['File Lock Protection', 'Enforces mandatory file locks on critical configuration files'],
    ['ACL Inheritance Audit', 'Audits ACL inheritance chains for permission escalation vectors'],
    ['Sparse File Detection', 'Detects malicious use of sparse files to bypass size-based scanners'],
    ['Transaction Log Monitor', 'Monitors NTFS transaction logs for unauthorized file modifications'],
  ],
  networkDefense: [
    ['Port Scan Detection', 'Detects and blocks port scanning attempts via SYN flood pattern analysis'],
    ['DDoS Mitigation', 'Mitigates distributed denial-of-service attacks through rate limiting'],
    ['Packet Anomaly Detection', 'Analyzes packet structure for malformed or crafted network packets'],
    ['IP Reputation Filtering', 'Filters traffic based on real-time IP reputation intelligence feeds'],
    ['Protocol State Validation', 'Validates TCP state transitions to detect session hijacking attempts'],
    ['DNS Tunneling Detection', 'Detects DNS tunneling by analyzing query entropy and payload sizes'],
    ['SSL Inspection Engine', 'Performs deep SSL/TLS inspection to uncover encrypted threats'],
    ['ARP Spoofing Defense', 'Detects and prevents ARP spoofing attacks on local network segments'],
    ['Traffic Pattern Learning', 'Builds baseline traffic patterns to detect anomalous network behavior'],
    ['Connection Rate Limiter', 'Limits new connection rates per source to prevent resource exhaustion'],
  ],
  registryProtection: [
    ['Run Key Monitor', 'Monitors Run and RunOnce registry keys for persistence malware'],
    ['Service Registry Guard', 'Protects service configuration registry entries from modification'],
    ['AppInit DLL Detection', 'Detects malicious AppInit_DLLs registry entries used for DLL injection'],
    ['Image Hijack Prevention', 'Prevents Image File Execution Options hijacking attacks'],
    ['WOW64 Registry Isolation', 'Isolates WOW64 registry redirects to prevent cross-architecture attacks'],
    ['Registry ACL Hardening', 'Hardens ACLs on sensitive registry hives against unauthorized access'],
    ['Startup Key Scanner', 'Scans all startup-related registry locations for unauthorized entries'],
    ['COM Registration Monitor', 'Monitors COM class registration changes for hijacking attempts'],
    ['Winlogon Hook Detection', 'Detects unauthorized modifications to Winlogon registry settings'],
    ['Registry Transaction Log', 'Maintains audit log of all registry write operations for forensics'],
  ],
  bootProtection: [
    ['MBR Integrity Check', 'Verifies Master Boot Record integrity against known-good baseline'],
    ['UEFI Secure Boot Enforcement', 'Enforces UEFI Secure Boot policy to prevent unsigned bootloaders'],
    ['Bootkit Detection', 'Scans for bootkit infections in VBR and early boot stages'],
    ['BCD Store Protection', 'Protects Boot Configuration Data store from tampering'],
    ['Kernel Load Verification', 'Verifies kernel image signature before allowing system boot'],
    ['Boot Log Analysis', 'Analyzes boot logs for anomalies indicating tampering attempts'],
    ['Early Launch Anti-Malware', 'Initiates anti-malware protection before third-party drivers load'],
    ['Firmware Rootkit Scanner', 'Scans firmware for rootkit implants during boot sequence'],
    ['Boot Path Whitelisting', 'Whitelists authorized boot paths and blocks unknown boot sources'],
    ['TPM Boot Measurement', 'Uses TPM to measure boot chain integrity via PCR registers'],
  ],
  injectionDefense: [
    ['DLL Injection Block', 'Blocks unauthorized DLL injection via SetWindowsHookEx and similar APIs'],
    ['Thread Injection Detection', 'Detects CreateRemoteThread-based injection into protected processes'],
    ['APC Injection Prevention', 'Prevents Asynchronous Procedure Call injection techniques'],
    ['Process Hollowing Guard', 'Detects process hollowing by comparing PE image in memory vs disk'],
    ['Atom Bombing Detection', 'Detects atom table-based code injection techniques'],
    ['Reflective DLL Detection', 'Scans for reflectively loaded DLLs missing from loader records'],
    ['Window Subclass Monitor', 'Monitors window subclassing for malicious message hook injection'],
    ['Extra Window Bytes Guard', 'Protects extra window memory bytes from code injection misuse'],
    ['Clipboard Injection Block', 'Blocks code injection through clipboard format manipulation'],
    ['Named Pipe Injection Scan', 'Scans named pipe communications for injected code payloads'],
  ],
  pipeSecurity: [
    ['Named Pipe ACL', 'Enforces strict ACLs on named pipe creation to prevent squatting'],
    ['Pipe Impersonation Block', 'Blocks pipe server impersonation attempts from untrusted clients'],
    ['Anonymous Pipe Hardening', 'Restricts anonymous pipe access to authorized processes only'],
    ['Pipe Message Validation', 'Validates pipe message integrity with cryptographic signatures'],
    ['Pipe Enumeration Guard', 'Prevents unauthorized enumeration of active named pipes'],
    ['Pipe Buffer Overflow Shield', 'Protects against buffer overflow attacks in pipe read/write operations'],
    ['Pipe Instance Limit', 'Limits pipe instance creation to prevent resource exhaustion'],
    ['Asynchronous Pipe Monitor', 'Monitors asynchronous pipe I/O for anomalous patterns'],
    ['Pipe Timeout Enforcement', 'Enforces timeout limits on pipe operations to prevent deadlocks'],
    ['Pipe Namespace Isolation', 'Isolates pipe namespaces per session to prevent cross-session attacks'],
  ],
  driverProtection: [
    ['Driver Signature Enforcement', 'Blocks loading of unsigned or improperly signed kernel drivers'],
    ['Driver IOCTL Filtering', 'Filters IOCTL requests to drivers for malicious command patterns'],
    ['Driver Load Notification', 'Registers load notifications to audit all driver loading events'],
    ['Vulnerable Driver Blocklist', 'Maintains blocklist of drivers with known exploitable vulnerabilities'],
    ['Driver Dispatch Table Guard', 'Protects driver dispatch tables from runtime hooking'],
    ['Driver Memory Isolation', 'Isolates driver memory pools from user-mode tampering'],
    ['IRP Handler Validation', 'Validates IRP handler integrity against known-good driver images'],
    ['Driver Object Callback Audit', 'Audits driver object callbacks for unauthorized modifications'],
    ['Device Stack Protection', 'Protects device stack from filter driver insertion attacks'],
    ['Driver Unload Prevention', 'Prevents forced unloading of critical security drivers'],
  ],
  codeObfuscation: [
    ['Control Flow Flattening', 'Flattens control flow graph to obscure program logic structure'],
    ['String Encryption', 'Encrypts embedded strings to prevent static analysis extraction'],
    ['Opaque Predicate Insertion', 'Inserts opaque predicates to complicate reverse engineering efforts'],
    ['Dead Code Injection', 'Injects dead code paths to increase binary complexity'],
    ['Virtualization Obfuscation', 'Converts native code to custom virtual machine bytecode'],
    ['Import Table Obfuscation', 'Obfuscates import address table to hide API usage'],
    ['Branch Function Chaining', 'Chains function calls through branch functions to obscure call graph'],
    ['Constant Data Encoding', 'Encodes constant data values with runtime decode routines'],
    ['Anti-Debug Code Generation', 'Generates anti-debugging code sequences at compilation time'],
    ['Metadata Stripping', 'Strips debug metadata and symbol information from binaries'],
  ],
  apiProtection: [
    ['API Call Validation', 'Validates API call parameters against expected value ranges'],
    ['Syscall Direct Invocation', 'Uses direct syscall invocation to bypass user-mode API hooks'],
    ['API Rate Limiting', 'Enforces rate limits on sensitive API calls to prevent abuse'],
    ['Return Value Sanitization', 'Sanitizes API return values to prevent information leakage'],
    ['Handle Validation', 'Validates handle parameters before passing to kernel APIs'],
    ['API Caller Verification', 'Verifies API caller identity via stack walk analysis'],
    ['Indirect Call Guard', 'Protects indirect call targets from redirection attacks'],
    ['API Result Caching', 'Caches authorized API results to reduce attack surface exposure'],
    ['Thunk Table Integrity', 'Verifies thunk table integrity at load time and periodically'],
    ['Parameter Boundary Check', 'Enforces strict boundary checking on all API buffer parameters'],
  ],
  stackProtection: [
    ['Stack Canary Verification', 'Places and verifies stack canaries to detect buffer overflows'],
    ['Shadow Stack', 'Maintains shadow stack for return address integrity verification'],
    ['Stack Frame Validation', 'Validates stack frame structure before each function prologue'],
    ['Variable Reordering', 'Randomizes local variable layout to thwart deterministic exploits'],
    ['SafeSEH Enforcement', 'Enforces Safe Structured Exception Handling chain validation'],
    ['Stack Depth Monitoring', 'Monitors stack depth to detect stack pivoting and ROP attacks'],
    ['Non-Executable Stack', 'Ensures stack memory pages are marked non-executable'],
    ['Stack Cookie Diversification', 'Diversifies stack cookies per module and per thread'],
    ['Uninitialized Variable Detection', 'Detects use of uninitialized stack variables via pattern analysis'],
    ['Enclave Stack Isolation', 'Isolates enclave stacks from main thread stacks for SGX protection'],
  ],
  vulnDetection: [
    ['Fuzzing Integration', 'Integrates fuzzing harness to discover input validation vulnerabilities'],
    ['Static Analysis Engine', 'Performs static code analysis for known vulnerability patterns'],
    ['Dynamic Taint Tracking', 'Tracks tainted data flow dynamically to find injection points'],
    ['CVE Database Sync', 'Syncs with CVE databases to detect known vulnerable components'],
    ['Binary Similarity Analysis', 'Compares binary code against vulnerability signature database'],
    ['Race Condition Detection', 'Detects potential race conditions via concurrent access analysis'],
    ['Integer Overflow Check', 'Detects integer overflow vulnerabilities in arithmetic operations'],
    ['Format String Scanner', 'Scans for format string vulnerabilities in logging functions'],
    ['Dependency Vulnerability Scan', 'Scans software dependencies for known security vulnerabilities'],
    ['Patch Gap Analysis', 'Analyzes patch gaps between vendor releases and applied patches'],
  ],
  privilegeControl: [
    ['Least Privilege Enforcement', 'Enforces least privilege principle on all process operations'],
    ['Token Privilege Audit', 'Audits security token privileges for unnecessary elevations'],
    ['UAC Bypass Detection', 'Detects and blocks User Account Control bypass techniques'],
    ['SeDebug Privilege Monitor', 'Monitors use of SeDebugPrivilege for unauthorized process access'],
    ['Admin Group Audit', 'Audits local administrator group membership changes'],
    ['Service Privilege Restriction', 'Restricts service account privileges to minimum required scope'],
    ['Token Integrity Level Guard', 'Enforces integrity level checks on inter-process operations'],
    ['Privileged File Operation Monitor', 'Monitors privileged file operations for security policy violations'],
    ['Scheduled Task Privilege Check', 'Validates scheduled task privilege levels against security baseline'],
    ['Remote Desktop Permission Audit', 'Audits remote desktop connection permissions for anomalies'],
  ],
  sleepProtection: [
    ['Sleep Obfuscation', 'Obfuscates sleep intervals to defeat timing-based detection'],
    ['Sleep Skip Detection', 'Detects when sleep functions are skipped by debuggers or sandboxes'],
    ['Timing Attack Defense', 'Randomizes sleep durations to prevent timing side-channel attacks'],
    ['Sleep Hook Detection', 'Detects hooks on sleep-related API functions'],
    ['Power State Monitor', 'Monitors system power state transitions for tampering'],
    ['Wake Event Validation', 'Validates wake event sources for unauthorized wake triggers'],
    ['Sleep Patch Guard', 'Protects sleep-related kernel structures from patching'],
    ['Hibernation Security', 'Secures hibernation file against offline tampering'],
    ['Fast Startup Monitor', 'Monitors fast startup configuration for persistence attempts'],
    ['Sleep Cycle Encryption', 'Encrypts sensitive data during sleep state transitions'],
  ],
  timestampDefense: [
    ['Timestamp Spoof Detection', 'Detects spoofed timestamps on files and network packets'],
    ['NTP Hardening', 'Hardens NTP client against time-shifting attacks'],
    ['Clock Drift Analysis', 'Analyzes clock drift patterns for VM detection evasion attempts'],
    ['Timestamp ACL Audit', 'Audits timestamp modification permissions on critical files'],
    ['Log Timestamp Integrity', 'Ensures log entry timestamps are cryptographically signed'],
    ['Kerberos Time Sync', 'Synchronizes time for Kerberos ticket validation security'],
    ['Hardware Clock Protection', 'Protects hardware RTC from unauthorized modification'],
    ['Timestamp Chain Verification', 'Verifies chronological consistency of audit trail timestamps'],
    ['Time Zone Manipulation Guard', 'Blocks unauthorized time zone changes that mask activity'],
    ['Epoch Boundary Check', 'Detects epoch rollover attacks on timestamp-based systems'],
  ],
  hookProtection: [
    ['IAT Hook Detection', 'Detects Import Address Table hooks via disk vs memory comparison'],
    ['EAT Hook Detection', 'Detects Export Address Table modifications in loaded modules'],
    ['Inline Hook Scanner', 'Scans for inline hooks by checking prologue byte integrity'],
    ['SSDT Hook Detection', 'Detects System Service Descriptor Table hooks in kernel'],
    ['IRP Hook Detection', 'Detects IRP dispatch table hooks in driver objects'],
    ['VTable Hook Guard', 'Protects virtual function tables from runtime hijacking'],
    ['Message Hook Monitor', 'Monitors Windows message hooks for keylogging attempts'],
    ['Event Hook Validation', 'Validates event hook chain integrity against whitelist'],
    ['COM Hook Detection', 'Detects COM interface method hooks via vtable verification'],
    ['Exception Handler Hook Scan', 'Scans exception handler chains for unauthorized entries'],
  ],
  accountSecurity: [
    ['Brute Force Detection', 'Detects brute force login attempts via failure rate analysis'],
    ['Password Policy Enforcement', 'Enforces strong password complexity and rotation policies'],
    ['Account Lockout Protection', 'Implements intelligent account lockout with progressive delays'],
    ['Pass-the-Hash Detection', 'Detects pass-the-hash attacks via authentication pattern analysis'],
    ['Golden Ticket Detection', 'Detects forged Kerberos golden tickets via anomaly scoring'],
    ['Silver Ticket Detection', 'Detects Kerberos silver ticket attacks on service accounts'],
    ['DCSync Attack Detection', 'Detects directory replication service abuse attempts'],
    ['Admin Account Monitoring', 'Monitors privileged account usage for anomalous activity'],
    ['Service Account Hardening', 'Hardens service accounts with managed identities and rotation'],
    ['Guest Account Lockdown', 'Disables and monitors guest account access attempts'],
  ],
  callbackProtection: [
    ['Callback Registration Monitor', 'Monitors kernel callback registrations for unauthorized entries'],
    ['Process Notify Callback Guard', 'Protects process creation notification callbacks'],
    ['Thread Notify Callback Guard', 'Protects thread creation notification callbacks'],
    ['Image Load Callback Guard', 'Protects image load notification callbacks from tampering'],
    ['Registry Callback Validation', 'Validates registry operation callbacks for integrity'],
    ['Object Manager Callback Audit', 'Audits object manager pre/post operation callbacks'],
    ['MiniFilter Callback Protection', 'Protects minifilter driver callbacks from removal'],
    ['Power Callback Monitor', 'Monitors power management callbacks for suspicious entries'],
    ['BugCheck Callback Guard', 'Protects bug check callback chain from exploitation'],
    ['Callback Priority Enforcement', 'Enforces callback execution priority for security modules'],
  ],
  dnsDefense: [
    ['DNSSEC Validation', 'Validates DNS responses with DNSSEC cryptographic signatures'],
    ['DNS over HTTPS Security', 'Secures DoH connections with certificate pinning'],
    ['DNS Cache Poisoning Defense', 'Prevents DNS cache poisoning via query ID randomization'],
    ['DNS Rebinding Protection', 'Blocks DNS rebinding attacks by validating response addresses'],
    ['NXDOMAIN Flood Detection', 'Detects NXDOMAIN response floods indicating DGA malware'],
    ['DNS Query Logging', 'Logs all DNS queries for forensic analysis and threat hunting'],
    ['Sinkhole Integration', 'Routes known malicious domains to sinkhole servers'],
    ['DNS Exfiltration Detection', 'Detects data exfiltration via DNS query payload analysis'],
    ['EDNS0 Validation', 'Validates EDNS0 extension parameters for abuse patterns'],
    ['DNS Zone Transfer Monitor', 'Monitors unauthorized DNS zone transfer attempts'],
  ],
  loginProtection: [
    ['Multi-Factor Authentication', 'Enforces multi-factor authentication for all login attempts'],
    ['Geolocation Login Check', 'Validates login geolocation against expected user locations'],
    ['Login Time Restriction', 'Enforces time-of-day restrictions on account access'],
    ['Concurrent Session Limit', 'Limits concurrent login sessions per user account'],
    ['Interactive Login Detection', 'Detects interactive vs non-interactive login patterns'],
    ['RDP Login Hardening', 'Hardens Remote Desktop Protocol login against brute force'],
    ['SSH Key Validation', 'Validates SSH key fingerprints before allowing authentication'],
    ['Login Anomaly Scoring', 'Scores login attempts based on behavioral anomaly models'],
    ['Credential Guard Integration', 'Integrates with Credential Guard for isolated credential storage'],
    ['Network Level Authentication', 'Enforces Network Level Authentication for remote logins'],
  ],
  filechangeDefense: [
    ['Real-time File Monitor', 'Monitors file system changes in real-time with minifilter driver'],
    ['File Integrity Baseline', 'Creates cryptographic baselines for critical system files'],
    ['Unauthorized Change Alert', 'Alerts on unauthorized changes to protected file sets'],
    ['File Version Tracking', 'Maintains version history of changes to monitored files'],
    ['Change Rollback Capability', 'Provides rollback capability for unauthorized file modifications'],
    ['File Change Rate Limit', 'Detects rapid file changes indicating ransomware activity'],
    ['Extension Change Monitor', 'Monitors suspicious file extension changes'],
    ['Shadow Copy Protection', 'Protects Volume Shadow Copy snapshots from deletion'],
    ['File Owner Change Audit', 'Audits file ownership changes for privilege escalation attempts'],
    ['Alternate Stream Change Guard', 'Monitors NTFS alternate stream creation and modification'],
  ],
  clipboardSecurity: [
    ['Clipboard Access Audit', 'Audits all clipboard access events for data theft detection'],
    ['Clipboard Content Filtering', 'Filters sensitive data patterns from clipboard content'],
    ['Clipboard Timeout Enforcement', 'Clears clipboard content after configurable timeout'],
    ['Clipboard Format Validation', 'Validates clipboard format types for injection attacks'],
    ['Sensitive Data Detection', 'Detects credit card, SSN, and password patterns in clipboard'],
    ['Clipboard Viewer Block', 'Blocks unauthorized clipboard viewer registration'],
    ['Clipboard History Protection', 'Secures clipboard history from unauthorized enumeration'],
    ['Cross-Session Clipboard Guard', 'Prevents clipboard access across different user sessions'],
    ['Clipboard Delay Paste Attack', 'Detects delay paste attack patterns used by malware'],
    ['Clipboard Metadata Scrubbing', 'Removes metadata from clipboard content before sharing'],
  ],
  keyboardProtection: [
    ['Keylogger Detection', 'Detects kernel and user-mode keyloggers via hook analysis'],
    ['Keyboard Filter Driver', 'Installs keyboard filter driver for input sanitization'],
    ['Keystroke Encryption', 'Encrypts keystrokes in kernel before delivering to applications'],
    ['Input Method Security', 'Secures input method editor against injection attacks'],
    ['Keyboard Layout Monitor', 'Monitors keyboard layout changes for key remapping attacks'],
    ['Virtual Keyboard Isolation', 'Isolates virtual keyboard input from physical keyboard hooks'],
    ['Scan Code Validation', 'Validates keyboard scan codes against expected hardware patterns'],
    ['Keyboard Input Rate Limit', 'Detects abnormal keyboard input rates from automation tools'],
    ['HID Device Authentication', 'Authenticates HID keyboard devices via descriptor validation'],
    ['Keyboard Debug Port Guard', 'Blocks access to keyboard debugging ports to prevent sniffing'],
  ],
  printSecurity: [
    ['Print Job Audit', 'Audits all print jobs for sensitive document leakage'],
    ['Print Spooler Hardening', 'Hardens print spooler service against privilege escalation'],
    ['Network Print Encryption', 'Encrypts print jobs transmitted over network protocols'],
    ['Print Driver Validation', 'Validates print driver signatures before installation'],
    ['Print Queue Protection', 'Protects print queues from unauthorized job manipulation'],
    ['Secure Print Release', 'Requires user authentication at printer for document release'],
    ['Print Metadata Scrubbing', 'Removes sensitive metadata from print job descriptors'],
    ['Print Port Monitor Guard', 'Monitors print port monitor installations for backdoors'],
    ['Print Nightmare Defense', 'Protects against PrintNightmare vulnerability variants'],
    ['Print Server Isolation', 'Isolates print server from domain controller compromise'],
  ],
  dnsProtection: [
    ['DNS-over-TLS Enforcement', 'Enforces DNS-over-TLS for encrypted DNS query transport'],
    ['DNS Query Anomaly Detection', 'Detects anomalous DNS query patterns via machine learning'],
    ['DNS Server Hardening', 'Hardens recursive DNS resolver against amplification attacks'],
    ['DNSSEC Key Management', 'Manages DNSSEC signing keys with automated rollover'],
    ['DNS Firewall Rules', 'Applies DNS firewall rules based on threat intelligence feeds'],
    ['DNS Response Validation', 'Validates DNS response integrity with query matching'],
    ['DNS Split Horizon', 'Implements split-horizon DNS for internal vs external queries'],
    ['DNS Rate Limiting', 'Rate limits DNS queries to prevent resource exhaustion'],
    ['DNS Log Correlation', 'Correlates DNS logs with other security event sources'],
    ['DNS Anycast Protection', 'Secures anycast DNS infrastructure against hijacking'],
  ],
  dhcpDefense: [
    ['DHCP Snooping', 'Enables DHCP snooping to prevent rogue DHCP server attacks'],
    ['DHCP Starvation Defense', 'Detects and blocks DHCP starvation attacks via MAC limiting'],
    ['DHCP Scope Protection', 'Protects DHCP scope configuration from unauthorized changes'],
    ['DHCP Option Validation', 'Validates DHCP options for malicious parameter injection'],
    ['DHCP Lease Monitoring', 'Monitors DHCP lease assignments for anomalous patterns'],
    ['DHCPv6 Security', 'Secures DHCPv6 against rogue RA and DHCPv6 server attacks'],
    ['DHCP Relay Protection', 'Protects DHCP relay agents from relay-based attacks'],
    ['DHCP Fingerprinting', 'Fingerprints DHCP clients to detect unauthorized devices'],
    ['DHCP Log Analysis', 'Analyzes DHCP logs for reconnaissance and spoofing attempts'],
    ['DHCP Failover Security', 'Secures DHCP failover communications with encryption'],
  ],
  arpProtection: [
    ['ARP Spoofing Detection', 'Detects ARP spoofing via MAC-to-IP mapping validation'],
    ['Static ARP Entry Enforcement', 'Enforces static ARP entries for critical infrastructure'],
    ['ARP Rate Limiting', 'Rate limits ARP requests to prevent cache poisoning floods'],
    ['Gratuitous ARP Validation', 'Validates gratuitous ARP announcements for MITM attempts'],
    ['ARP Table Integrity Check', 'Periodically verifies ARP table consistency across switches'],
    ['Dynamic ARP Inspection', 'Enables dynamic ARP inspection on managed switches'],
    ['ARP Poisoning Alert', 'Generates real-time alerts on detected ARP poisoning events'],
    ['IPv6 NDP Protection', 'Protects IPv6 neighbor discovery from spoofing attacks'],
    ['ARP Cache Timeout Tuning', 'Tunes ARP cache timeouts to minimize poisoning windows'],
    ['VLAN ARP Isolation', 'Isolates ARP traffic within VLAN boundaries'],
  ],
  bluetoothSecurity: [
    ['Bluetooth Device Whitelist', 'Whitelists authorized Bluetooth devices by MAC address'],
    ['Bluetooth Pairing Validation', 'Requires secure pairing method validation for connections'],
    ['Bluetooth Discovery Control', 'Controls Bluetooth discoverability based on security policy'],
    ['Bluetooth Traffic Encryption', 'Enforces encryption on all Bluetooth data traffic'],
    ['Bluetooth PIN Hardening', 'Requires strong PIN authentication for legacy Bluetooth pairing'],
    ['BlueBorne Attack Defense', 'Protects against BlueBorne over-the-air attack vectors'],
    ['Bluetooth Service Audit', 'Audits available Bluetooth services for unauthorized profiles'],
    ['Bluetooth Range Enforcement', 'Enforces Bluetooth transmit power limits for access control'],
    ['Bluetooth Firmware Validation', 'Validates Bluetooth controller firmware integrity'],
    ['Bluetooth Sniffing Detection', 'Detects passive Bluetooth sniffing via probe pattern analysis'],
  ],
  wifiSecurity: [
    ['WPA3 Enforcement', 'Enforces WPA3-Enterprise with 192-bit encryption for WiFi networks'],
    ['Rogue AP Detection', 'Detects rogue access points via beacon frame analysis'],
    ['Evil Twin Defense', 'Defends against evil twin AP attacks with certificate validation'],
    ['WiFi Deauth Protection', 'Protects against deauthentication frame flooding attacks'],
    ['PMKID Attack Prevention', 'Prevents PMKID-based WPA hash capture attacks'],
    ['Wireless Client Isolation', 'Isolates wireless clients from each other on same SSID'],
    ['WiFi MAC Filtering', 'Filters WiFi clients by MAC address whitelist'],
    ['EAP-TLS Certificate Validation', 'Validates EAP-TLS certificates for RADIUS authentication'],
    ['WiFi Probe Request Monitoring', 'Monitors probe requests for device tracking attempts'],
    ['KRACK Attack Defense', 'Defends against key reinstallation attacks on WPA2 handshake'],
  ],
  usbProtection: [
    ['USB Device Authorization', 'Requires authorization for all USB device connections'],
    ['USB Mass Storage Block', 'Blocks USB mass storage devices per security policy'],
    ['USB Rubber Ducky Defense', 'Detects USB Rubber Ducky attacks via typing speed analysis'],
    ['USB Device Fingerprinting', 'Fingerprints USB devices by descriptor and behavior patterns'],
    ['USB DMA Attack Prevention', 'Prevents DMA attacks through Thunderbolt/USB4 interfaces'],
    ['USB Hub Security', 'Monitors USB hub tree for unauthorized device insertion'],
    ['USB Descriptor Validation', 'Validates USB device descriptors for malformed attacks'],
    ['USB Charge-Only Mode', 'Enforces charge-only mode on untrusted USB connections'],
    ['USB Data Leak Prevention', 'Prevents data exfiltration via USB storage devices'],
    ['USB Firmware Validation', 'Validates USB device firmware against known-good signatures'],
  ],
  logSecurity: [
    ['Log Tamper Detection', 'Detects tampering with security log files via integrity checks'],
    ['Log Encryption', 'Encrypts log data at rest and in transit to SIEM'],
    ['Log Retention Enforcement', 'Enforces log retention policies per compliance requirements'],
    ['Log Access Control', 'Restricts log access to authorized security personnel only'],
    ['Log Forwarding Security', 'Secures log forwarding channels with mutual TLS authentication'],
    ['Log Format Validation', 'Validates log entry format to prevent log injection attacks'],
    ['Centralized Log Collection', 'Collects logs centrally with high-availability storage'],
    ['Log Anomaly Detection', 'Detects anomalies in log patterns indicating security incidents'],
    ['Log Metadata Integrity', 'Preserves log metadata including original timestamps and sources'],
    ['Log Backup Strategy', 'Implements secure log backup with offsite storage replication'],
  ],
  scheduledTask: [
    ['Task Creation Audit', 'Audits scheduled task creation events for persistence malware'],
    ['Task XML Validation', 'Validates scheduled task XML for malicious trigger configurations'],
    ['Task Privilege Check', 'Verifies scheduled task privilege levels match security policy'],
    ['Task Action Hardening', 'Restricts task action types to authorized executables only'],
    ['Task Trigger Validation', 'Validates task triggers for anomalous scheduling patterns'],
    ['Task Deletion Protection', 'Protects critical scheduled tasks from unauthorized deletion'],
    ['Task DLL Injection Guard', 'Prevents DLL injection via custom task COM handler abuse'],
    ['Task Run As Validation', 'Validates RunAs user context for scheduled tasks'],
    ['Task Network Condition Guard', 'Monitors network condition task triggers for abuse'],
    ['Task Hidden Attribute Detection', 'Detects hidden scheduled tasks used for stealth persistence'],
  ],
  restorePoint: [
    ['Restore Point Creation', 'Creates system restore points before critical changes'],
    ['Restore Point Integrity', 'Verifies restore point integrity with cryptographic hashes'],
    ['Restore Point Protection', 'Protects restore points from ransomware deletion attempts'],
    ['Restore Point Encryption', 'Encrypts restore point data to prevent offline tampering'],
    ['Restore Point Schedule', 'Schedules automatic restore point creation at policy intervals'],
    ['Restore Point Quota', 'Manages restore point storage quotas to prevent disk exhaustion'],
    ['Restore Point Verification', 'Verifies restore point recoverability with test restores'],
    ['Restore Point Forensics', 'Preserves restore points for forensic investigation purposes'],
    ['Restore Point Rollback Guard', 'Guards against unauthorized system restore rollbacks'],
    ['Restore Point Differential', 'Uses differential storage to minimize restore point size'],
  ],
  serviceProtection: [
    ['Service ACL Hardening', 'Hardens Windows service ACLs to prevent unauthorized control'],
    ['Service Binary Protection', 'Protects service binary files from replacement attacks'],
    ['Service Account Isolation', 'Isolates service accounts with unique low-privilege SIDs'],
    ['Service Failure Monitoring', 'Monitors service failure patterns for crash-based attacks'],
    ['Service Dependency Audit', 'Audits service dependency chains for hijacking vectors'],
    ['Service Configuration Lock', 'Locks critical service configurations from modification'],
    ['Service Restart Policy', 'Enforces security-monitored service restart policies'],
    ['Service Install Detection', 'Detects unauthorized service installation attempts'],
    ['Service SID Type Validation', 'Validates service SID types for least-privilege compliance'],
    ['Service Delayed Auto-Start Guard', 'Monitors delayed auto-start services for malware abuse'],
  ],
  permissionSync: [
    ['Permission Baseline Sync', 'Syncs file permissions to security baseline on schedule'],
    ['Permission Drift Detection', 'Detects permission drift from baseline configuration'],
    ['ACL Inheritance Enforcement', 'Enforces proper ACL inheritance on directory hierarchies'],
    ['Permission Remediation', 'Automatically remediates non-compliant permission settings'],
    ['Cross-Platform Permission Sync', 'Syncs permissions across Windows and Unix file systems'],
    ['Permission Change Audit', 'Audits all permission changes with before/after snapshots'],
    ['Role-Based Permission Model', 'Maps permissions to security roles for consistent enforcement'],
    ['Permission Propagation Control', 'Controls permission propagation to prevent unintended access'],
    ['Stale Permission Cleanup', 'Identifies and removes stale permissions from inactive accounts'],
    ['Delegated Permission Review', 'Reviews delegated permissions for over-privileged grants'],
  ],
  apiAudit: [
    ['API Call Logging', 'Logs all sensitive API calls with parameter context'],
    ['API Anomaly Detection', 'Detects anomalous API call sequences via behavioral modeling'],
    ['API Rate Anomaly', 'Identifies abnormal API call rates indicating automation attacks'],
    ['API Parameter Taint', 'Tracks tainted parameters through API call chains'],
    ['API Privilege Escalation', 'Detects API-based privilege escalation attempts'],
    ['API Handle Misuse', 'Detects handle misuse patterns across API call boundaries'],
    ['API Caller Context', 'Captures caller identity and integrity for API audit trails'],
    ['API Response Validation', 'Validates API responses for data leakage patterns'],
    ['API Token Audit', 'Audits API token usage for unauthorized access patterns'],
    ['API Error Rate Monitor', 'Monitors API error rates for probing and fuzzing attempts'],
  ],
  injectionImmune: [
    ['Code Cave Scanner', 'Scans for code caves used to host injected shellcode'],
    ['Thread Start Address Audit', 'Audits thread start addresses against legitimate module ranges'],
    ['Memory Section Mapping', 'Detects manually mapped modules via section object analysis'],
    ['Kernel Callback Injection Defense', 'Blocks injection via kernel callback modification'],
    ['SetContextThread Detection', 'Detects injection via SetContextThread register manipulation'],
    ['Fiber Injection Defense', 'Prevents code execution via fiber scheduling injection'],
    ['Early Bird Injection Detection', 'Detects early bird APC injection during process creation'],
    ['Mapping Injection Detection', 'Detects section mapping injection via NtMapViewOfSection'],
    ['ALPC Injection Block', 'Blocks Advanced Local Procedure Call-based injection techniques'],
    ['WNF Injection Defense', 'Prevents Windows Notification Facility subscription injection'],
  ],
  stackIsolation: [
    ['Stack Memory Encryption', 'Encrypts sensitive data on stack frames during execution'],
    ['Thread Stack Segregation', 'Segregates thread stacks with reserved guard regions'],
    ['Stack Usage Profiling', 'Profiles stack usage patterns to detect overflow exploitation'],
    ['Stack Region Randomization', 'Randomizes stack base addresses per thread creation'],
    ['Call Stack Validation', 'Validates call stack integrity via frame pointer chains'],
    ['Stack Exhaustion Detection', 'Detects stack exhaustion attacks that trigger guard pages'],
    ['Shadow Call Stack', 'Implements shadow call stack for ARM-based platforms'],
    ['Stack Write Protection', 'Write-protects inactive stack frames during function calls'],
    ['Stack-based IPC Isolation', 'Isolates stack-based IPC from main execution stacks'],
    ['Stack Frame Metadata', 'Adds cryptographic metadata to each stack frame for validation'],
  ],
  filesystemObfuscation: [
    ['Directory Name Obfuscation', 'Obfuscates security module directory names at runtime'],
    ['File Extension Camouflage', 'Uses legitimate-looking file extensions for security binaries'],
    ['MFT Entry Scrambling', 'Scrambles MFT entry ordering to confuse forensic tools'],
    ['Timestamp Randomization', 'Randomizes file timestamps to blend with system files'],
    ['File Size Padding', 'Pads security module files to match common system file sizes'],
    ['Stream Diversification', 'Distributes code across multiple NTFS alternate streams'],
    ['Path Depth Obfuscation', 'Places files at varying directory depths to avoid scanners'],
    ['File Attribution Blending', 'Sets file attributes to match neighboring system files'],
    ['Sparse File Code Placement', 'Uses sparse file regions to hide code from linear scanners'],
    ['Log File Noise Injection', 'Injects noise into file system logs to mask security operations'],
  ],
  heapProtection: [
    ['Heap Metadata Protection', 'Protects heap metadata from corruption with checksums'],
    ['Heap Canary Placement', 'Places canary values between heap chunks for overflow detection'],
    ['Heap Randomization', 'Randomizes heap layout to prevent deterministic exploitation'],
    ['Heap Integrity Check', 'Performs periodic heap integrity verification sweeps'],
    ['Heap Isolation', 'Isolates sensitive allocations in separate heap partitions'],
    ['Heap Allocation Audit', 'Audits heap allocations for suspicious size and frequency patterns'],
    ['Heap Feng Shui Detection', 'Detects heap feng shui manipulation for exploit preparation'],
    ['LFH Isolation', 'Isolates Low Fragmentation Heap for sensitive allocations'],
    ['Heap Spray Pattern Recognition', 'Recognizes heap spray patterns via memory content analysis'],
    ['Heap Cookie Validation', 'Validates heap cookies before each allocation and deallocation'],
  ],
  aslrEnhancement: [
    ['High-Entropy ASLR', 'Enables high-entropy 64-bit address space randomization'],
    ['ASLR Force Relocation', 'Forces mandatory ASLR on all loaded modules'],
    ['ASLR Entropy Audit', 'Audits ASLR entropy to detect address space information leaks'],
    ['Module Base Randomization', 'Randomizes module base addresses with maximum entropy'],
    ['Heap ASLR Enforcement', 'Enforces heap address randomization per allocation'],
    ['Stack ASLR Hardening', 'Hardens stack ASLR with per-thread base randomization'],
    ['ASLR Bypass Detection', 'Detects ASLR bypass techniques via address pattern analysis'],
    ['PEB/TEB Randomization', 'Randomizes Process/Thread Environment Block locations'],
    ['JIT ASLR Integration', 'Integrates ASLR with JIT-compiled code page placement'],
    ['ASLR Compatibility Shim', 'Provides ASLR compatibility shim for legacy software'],
  ],
  tlsHardening: [
    ['TLS 1.3 Enforcement', 'Enforces TLS 1.3 with modern cipher suites'],
    ['Certificate Pinning', 'Pins server certificates to prevent MITM with forged certs'],
    ['TLS Cipher Suite Hardening', 'Restricts TLS cipher suites to strong algorithms only'],
    ['TLS Renegotiation Protection', 'Protects against TLS renegotiation DoS attacks'],
    ['HSTS Enforcement', 'Enforces HTTP Strict Transport Security for all connections'],
    ['TLS Session Resumption Security', 'Secures TLS session resumption with key rotation'],
    ['TLS Compression Defense', 'Disables TLS compression to prevent CRIME/BREACH attacks'],
    ['TLS Fallback Prevention', 'Prevents TLS protocol downgrade attacks via SCSV'],
    ['TLS Certificate Transparency', 'Validates certificates against CT logs for misissuance'],
    ['TLS Key Log Protection', 'Blocks SSLKEYLOGFILE-style key logging for debugging'],
  ],
  kernelBoot: [
    ['Secure Kernel Loading', 'Validates kernel image signature during boot'],
    ['Kernel Patch Protection', 'Enables PatchGuard to prevent kernel structure modification'],
    ['Boot Driver Ordering', 'Enforces secure boot driver loading order'],
    ['Kernel Debugger Block', 'Blocks kernel debugger attachment on production systems'],
    ['Hypervisor Integrity', 'Validates hypervisor integrity before kernel launch'],
    ['Measured Boot Chain', 'Implements measured boot with TPM attestation'],
    ['Kernel Code Signing', 'Enforces kernel-mode code signing for all modules'],
    ['Boot Configuration Lock', 'Locks boot configuration to prevent tampering'],
    ['Kernel Address Protection', 'Protects kernel address space from user-mode access'],
    ['Boot Integrity Measurement', 'Measures boot integrity via TPM Platform Configuration Registers'],
  ],
  driverSigning: [
    ['Cross-Signing Validation', 'Validates cross-signed driver certificates through chain'],
    ['Driver Certificate Revocation', 'Checks driver certificate revocation status at load time'],
    ['EV Certificate Enforcement', 'Requires Extended Validation certificates for kernel drivers'],
    ['Driver Signing Policy', 'Enforces driver signing policy via CI module configuration'],
    ['Driver Catalog Validation', 'Validates driver catalog files against trusted publishers'],
    ['Timestamp Countersignature', 'Requires valid timestamp countersignatures on driver packages'],
    ['Driver Hash Verification', 'Verifies driver image hash matches